#!/bin/bash
trap "echo -ne '\nstopping container...' && docker stop refinery-ui > /dev/null 2>&1 && echo -ne '\t\t [done]\n'" EXIT

docker stop refinery-ui

docker build -t refinery-ui-dev -f dev.Dockerfile .

docker run --rm -d \
--name refinery-ui \
-p 7050:80 \
--mount type=bind,source="$(pwd)"/,target=/app \
--network dev-setup_default \
refinery-ui-dev

docker logs -f refinery-ui
