export enum Status {
    CREATED = 'CREATED',
    RUNNING = 'RUNNING',
    STARTED = 'STARTED',
    FINISHED = 'FINISHED',
    FAILED = 'FAILED',
    USABLE = 'USABLE',
    UPLOADED = 'UPLOADED',
    READY = 'READY',
    UPDATING = 'UPDATING',
    NOT_READY = 'NOT_READY',
    QUEUED = 'QUEUED',
    AUTOMATICALLY_CREATED = 'AUTOMATICALLY_CREATED',
}